# Processing and cleaning the cropland dataset

In [17]:
import cropland
import importlib
importlib.reload(cropland)
roi = (68.57419, 20.10456, 74.48682,24.71818)

In [18]:
df_cropland= cropland.preprocess_rasterio(cropland.read_file(f'../dataset/cropland/Global_cropland_3km_2019.tif'), roi=roi)
netgain = cropland.preprocess_rasterio(cropland.read_file('../dataset/cropland/Global_cropland_3km_netgain.tif'), roi=roi)

In [19]:
import pandas as pd

cropland = df_cropland.set_index(['lat', 'lon'])
netgain = netgain.set_index(['lat', 'lon'])

# join them
cropland = cropland.join(netgain, how='left', rsuffix='_netgain')

In [23]:
cropland = cropland.reset_index()
cropland.to_csv('../dataset/cropland/cropland.csv', index=False)

In [14]:
import district

df = district.DISTRICTS

,objectid,statecode,statename,state_ut,distcode,distname,distarea,totalpopul,totalhh,totpopmale,totpopfema,st_areasha,st_lengths,geometry
0,1,05,Uttarakhand,STATE,066,Nainital,4251.0,954605.0,191383.0,493666.0,460939.0,5.322546e+09,5.061827e+05,"POLYGON ((79.52659 29.05543, 79.52550 29.05545..."
1,2,05,Uttarakhand,STATE,060,Dehradun,3088.0,1696694.0,347001.0,892199.0,804495.0,4.177236e+09,5.781887e+05,"POLYGON ((77.87557 30.26052, 77.87467 30.26087..."
2,3,05,Uttarakhand,STATE,064,Almora,3144.0,622506.0,140577.0,291081.0,331425.0,4.140751e+09,4.634542e+05,"POLYGON ((79.28494 29.92735, 79.28495 29.92723..."
3,4,05,Uttarakhand,STATE,065,Champawat,1766.0,259648.0,53953.0,131125.0,128523.0,2.294297e+09,3.145080e+05,"POLYGON ((80.12479 29.01308, 80.12481 29.01306..."
4,5,05,Uttarakhand,STATE,056,Uttarkashi,8016.0,330086.0,67602.0,168597.0,161489.0,1.085166e+10,7.864256e+05,"POLYGON ((78.92267 31.25333, 78.93106 31.26840..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688,691,36,Telangana,STATE,T28,Wanaparthy,NaN,577758.0,123544.0,294833.0,282925.0,2.471575e+09,2.894403e+05,"POLYGON ((78.23115 16.43789, 78.23471 16.38793..."
689,692,36,Telangana,STATE,T27,Vikarabad,NaN,927140.0,194956.0,463350.0,463790.0,3.978808e+09,3.723430e+05,"POLYGON ((77.41953 17.12279, 77.41852 17.12334..."
690,693,36,Telangana,STATE,T13,Mahabubnagar,NaN,1486777.0,300508.0,745101.0,741676.0,5.627610e+09,4.420680e+05,"POLYGON ((77.49606 16.38155, 77.49382 16.38188..."
691,41,01,Ladakh,STATE,004,Kargil,14036.0,140802.0,18338.0,77785.0,63017.0,2.152617e+10,1.151337e+06,"POLYGON ((76.13869 34.63398, 76.13957 34.63408..."
692,34,01,Ladakh,STATE,003,Leh (Ladakh),45110.0,133487.0,21909.0,78971.0,54516.0,1.181149e+11,2.283246e+06,"POLYGON ((80.06767 34.78624, 80.06849 34.77767..."